#-------------------------------------------------------------------------------
# Copyright (C) 2018 Eurotech and/or its affiliates
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     Eurotech
#-------------------------------------------------------------------------------
language: java

sudo: false

jdk:
  - oraclejdk8

env:
  global:
    - COMPONENT=agile-kura
    - DOCKER_CACHE_FILE=/home/travis/docker-cache/cache.tar.gz
  matrix:
    - VERSIONIST=true

before_install:
  - source <(curl -s https://raw.githubusercontent.com/Agile-IoT/agile-ci-scripts/master/agile-ci-functions.sh)

after_success:
  - versionist_if_needed